### ISSUE TITLE
Crash when opening the small chest

### ISSUE THREAD

**Issue by FRBFStudios** [lilnibblit/Chest-Alert#2]
When I open my small daily chest, the game crashes (but only on my Android phone, not on my PC). Disabling this mod fixes it.

Crashlog:

[Crash 2024-07-17 06.39.23.dmp](https://github.com/user-attachments/files/16260317/Crash.2024-07-17.06.39.23.dmp)

**Comment by dotnetx86** [comment]
uninstall pages api

**Comment by FRBFStudios** [comment]
okay thank you :) will you try to make it compatible?

**Comment by dotnetx86** [comment]
i will

**Comment by FRBFStudios** [comment]
fantastic, tysm!

**Comment by dotnetx86** [comment]
fixed
