### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Infernogd** [lilnibblit/Chest-Alert#3]
[2024-08-03_15-08-09.log](https://github.com/user-attachments/files/16482588/2024-08-03_15-08-09.log)

**Comment by dotnetx86** [comment]
when does it crash

**Comment by InfernoZv** [comment]
When the chest opens but it doesn't happen every time. Sorry for late response

**Comment by InfernoZv** [comment]
Did You Fix the issue? Since you updated it

**Comment by dotnetx86** [comment]
i think so
