### ISSUE TITLE
crash still happens

### ISSUE THREAD

**Issue by Infernogd** [lilnibblit/Chest-Alert#4]
yeah the crash happens still here is the log and a video so you can see
[2024-08-17_23-29-42.log](https://github.com/user-attachments/files/16650118/2024-08-17_23-29-42.log)

https://github.com/user-attachments/assets/c4f8786e-593f-4b1c-8da9-26de53741ed2

**Comment by dotnetx86** [comment]
[lilnibblit.chestalert.geode.zip](https://github.com/user-attachments/files/16681322/lilnibblit.chestalert.geode.zip)
try this version (delete .zip at the end of the name)

**Comment by InfernoZv** [comment]
I think its fixed like I said its a rare crash. Double Check For Any Crash Traces But what I seen Its All Good!
